### PR TITLE
Relax activesupport version

### LINKED ISSUE #45: Move ActiveSupport to dev dep rather than runtime dep
Having active support 4.1.5 as a runtime dep makes this gem incompatible with any app running Rails < 4.1. I could also not figure out why is this gem a dep at all but I may have missed the it when looking at the code.

### PR DESCRIPTION
**Pull request by carols10cents**
This would fix #45. This relaxes the version of activesupport so that people on rails 3.2 or rails 4.1 can both use clever-ruby and be confident that the functionality has been tested (through the use of the [Appraisal gem](https://github.com/thoughtbot/appraisal)).

### CODE REVIEW

**Comment by carols10cents** [comment]
Just added a commit updating this since rails 4.2 is out of beta-- let me know if you'd like these squashed and/or the merge of upstream rebased out, but I wanted to make it clear what I had updated :)

**Comment by osdiab** [comment]
Hi, I'm back after a year away :)

I think a better long-term solution is to rework this so it doesn't rely on `activesupport`—this dramatically increases the amount of time it takes to run tests and still requires active maintenance to worry about the rails versions that come out as they come out.

I'm going to see if I could make this work without the reliance on the inflector, which I believe is the only part of `activesupport` in use; especially since the number of resources is small.

**Comment by carols10cents** [comment]
> I'm going to see if I could make this work without the reliance on the inflector, which I believe is the only part of activesupport in use; especially since the number of resources is small.

That would be great, the fewer dependencies the better!

**Comment by osdiab** [comment]
relevant issue: #61

**Comment by carols10cents** [comment]
Looks like this is moot! #66

**Pull request closed without merging**
